### ISSUE TITLE
db name不对

### ISSUE THREAD

**Issue by helloworldtang** [lvhao/schedule-job#1]
TicketMapper.xml文件中有：
learn.t_ticket

配置文件中的db name是schedule_job

**Comment by lvhao** [comment]
感谢反馈，learn.t_ticket 库表用来搭建spring boot 框架及各种功能示例，schedule_job库 用来示例quartz,可以合并成一个库。

**Comment by zhao907219202** [comment]
动态数据源在启动时没有指定:
QuartzConfig 自动装配的数据源dataSource 有报错。

**Comment by lvhao** [comment]
请参考DynamicDatasource类上@Primary注解
